baseURL: https://nisabukeozer.netlify.app/
languageCode: en-us
title: Nisa Buke Ozer
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Start Exploring
    subtitle: |-
      Welcome to my portfolio!
    title: Nisa Buke Ozer
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Baker Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: nozer.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 07463468958
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Nisa Buke Ozer
    enable: yes
    #quicklinks:
     # - alt: HTML5 UP
      #  text: 'Design: '
       # url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/nisabukeozer
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nisabukeozer
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/nisabukeozer
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/nisabukeozer
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/nisabukeozer/
  image: ''
  name: Nisa Buke Ozer
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: sunset.JPG
        subtitle: If you would like to know who I am...
        title: About me!
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: My academic background
        title: Education
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: About my work experiences in Istanbul and London
        title: Professional Experience
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Data analytics projects that I worked on
        title: Projects
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: I especially love sunset photography!
        title: Photography
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Interesting tech news from around the globe
        title: Tech Blog
        url: blogs/ipsum
 # two:
    #buttonText: Start Exploring
    #enable: yes
    #subtitle: "My portfolio is diverse. "
    #title: Massa libero
    #url: blogs
