---
categories:
- ""
- ""
date: "2017-10-31T22:26:13-05:00"
description: The schools I attended
draft: false
image: youth.jpg
keywords: ""
slug: project5
title: Youth Risk Behavior Surveillance 
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p><strong>Aim:</strong>to analyse the health patterns of American high scholers (9th through 12th grade) using R libraries.</p>
<p><strong>Data:</strong> Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it.</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.37, 55.79, 46.72, 67.13, 131.54, 7…
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
<pre class="r"><code>yrbss %&gt;% mutate(race = factor(race))</code></pre>
<pre><code>## # A tibble: 13,583 × 13
##      age gender grade hispanic race    height weight helmet_12m text_while_driv…
##    &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;fct&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           
##  1    14 female 9     not      Black …  NA      NA   never      0               
##  2    14 female 9     not      Black …  NA      NA   never      &lt;NA&gt;            
##  3    15 female 9     hispanic Native…   1.73   84.4 never      30              
##  4    15 female 9     not      Black …   1.6    55.8 never      0               
##  5    15 female 9     not      Black …   1.5    46.7 did not r… did not drive   
##  6    15 female 9     not      Black …   1.57   67.1 did not r… did not drive   
##  7    15 female 9     not      Black …   1.65  132.  did not r… &lt;NA&gt;            
##  8    14 male   9     not      Black …   1.88   71.2 never      &lt;NA&gt;            
##  9    15 male   9     not      Black …   1.75   63.5 never      &lt;NA&gt;            
## 10    15 male   10    not      Black …   1.37   97.1 did not r… &lt;NA&gt;            
## # … with 13,573 more rows, and 4 more variables: physically_active_7d &lt;int&gt;,
## #   hours_tv_per_school_day &lt;chr&gt;, strength_training_7d &lt;int&gt;,
## #   school_night_hours_sleep &lt;chr&gt;</code></pre>
<pre class="r"><code>skimr::skim(yrbss) #to get a feel about the dataset</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-1">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.00</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.60</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.25</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.00</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p><strong>Starting out by analyzing the <code>weight</code> of participants in kilograms.</strong></p>
<pre class="r"><code>#number of missing values in the &#39;weight&#39; column:
sumna &lt;- sum(is.na(yrbss[&#39;weight&#39;]))
print(paste0(&quot;there are &quot; , sumna ,&quot; missing values.&quot; ))</code></pre>
<pre><code>## [1] &quot;there are 1004 missing values.&quot;</code></pre>
<pre class="r"><code>#using mosaic&#39;s favstats
favstats(~weight, data=yrbss)</code></pre>
<pre><code>##    min    Q1 median   Q3    max    mean       sd     n missing
##  29.94 56.25  64.41 76.2 180.99 67.9065 16.89821 12579    1004</code></pre>
<pre class="r"><code>#as it is also apparent in the favstat&#39;s function output, there are 1004 missing values in the weight column. 

#histogram of the weight distribution
  ggplot(yrbss, aes(x=weight))+
  geom_histogram(bindwidth=5, color =&quot;black&quot;, fill = &quot;white&quot;)+
  labs (title = &quot;Histogram of Weigth Distribution&quot;,
        y = &quot;Count&quot;,
        x = &quot;Weight (in kilograms)&quot;)+ 
  theme_bw()+
  geom_vline(aes(xintercept = mean(weight, na.rm = TRUE)), color=&quot;blue&quot;, linetype=&quot;dashed&quot;, size=1)+
  NULL</code></pre>
<pre><code>## Warning: Ignoring unknown parameters: bindwidth</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1004 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="/blogs/project5_files/figure-html/eda_on_weight-1.png" width="672" /></p>
<pre class="r"><code>#density plot of the weight distribution
  ggplot(yrbss, aes(x=weight)) +
  geom_density() +
  labs (title = &quot;Density Plot of Weight Distribution&quot;,
        x = &quot;Weight (in kilograms)&quot;)+
  theme_bw()+
  NULL</code></pre>
<pre><code>## Warning: Removed 1004 rows containing non-finite values (stat_density).</code></pre>
<p><img src="/blogs/project5_files/figure-html/eda_on_weight-2.png" width="672" /></p>
<p><strong>Is there a relationship between a high schooler’s weight and their physical activity?</strong>
By adding a new column that shows whether a student exercised more than 3 days a week or not, the relationship with exercises and non-exercises can be easily determined.</p>
<pre class="r"><code>yrbss %&gt;%
  filter(!is.na(physically_active_7d))%&gt;%
  ggplot(aes(x = factor(physically_active_7d))) +
  geom_boxplot(aes(y=weight))+
  labs (title = &quot;Distribution of Weight by Number of Active days in a week&quot;,
        x = &quot;Number of Active Days in a Week&quot;,
        y = &quot;weight (kg)&quot;) +
  theme_bw()</code></pre>
<pre><code>## Warning: Removed 946 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="/blogs/project5_files/figure-html/mutate_and_count-1.png" width="672" /></p>
<pre class="r"><code>  #adding the new variable `physical_3plus` that shows if a student is physically active 3 or more days a week. 
  physical &lt;- yrbss %&gt;% 
    mutate(physical_3plus = case_when(physically_active_7d &gt;= 3 ~ &quot;yes&quot;,
                                       physically_active_7d &lt; 3 ~ &quot;no&quot;),
          physical_3plus = factor(physical_3plus, levels = c(&quot;yes&quot;, &quot;no&quot;)))  
 
 count_physical &lt;- physical %&gt;% 
   filter(!is.na(physical_3plus)) %&gt;% 
   count(physical_3plus) %&gt;% 
   mutate(prop = n/sum(n))
 
 #5685, 2656 
 
 prop.test(count_physical$n[2]  , count_physical$n[2] + count_physical$n[1])</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  [ out of +count_physical$n out of count_physical$n[2]2 out of count_physical$n[1]
## X-squared = 1522.1, df = 1, p-value &lt; 2.2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.3228978 0.3389583
## sample estimates:
##        p 
## 0.330879</code></pre>
<p><strong>95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</strong></p>
<p>The 95 percent confidence interval according to the prop.test function is from 0.3228978 to 0.3389583.</p>
<p><em>data: [ out of +count_physical<span class="math inline">\(n out of count_physical\)</span>n[2]2 out of count_physical$n[1]
X-squared = 1522, df = 1, p-value &lt;2e-16
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
0.323 0.339
sample estimates:
p
0.331</em></p>
<p>Initial plotting of the data doesn’t suggest a strong correlation between weekly physical activity levels and weight.</p>
<p><strong>A boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? </strong></p>
<pre class="r"><code>#removing rows that contain NAs from the physical table... 
   physical &lt;- physical %&gt;% 
   filter(!is.na(physical_3plus) &amp; !is.na(weight))
   
#box plot of physical_3plus vs weight:
  
  ggplot(physical, aes(x=physical_3plus, y = weight)) +
  geom_boxplot()+
  labs (title = &quot;Distribution of Weight, Based on weekly activity level&quot;,
        x = &quot;Working out 3 or more days: Yes or No&quot;,
        y = &quot;weight (kg)&quot;) +
  theme_bw()</code></pre>
<p><img src="/blogs/project5_files/figure-html/boxplot-1.png" width="672" /></p>
<p>People who work out 3 days a week or more are slightly heavier on average. One might expect the opposite, but weight is not a great indicator of fitness levels as it varries widely with height, and the number of workout days might not indicate the intensity of the workouts either. We would expect a stronger negative correlation between bodyfat percentage and number of active days a week.</p>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>set.seed(1234)
#calculating CI using formulas:

#physical_3plus == &quot;yes
 yes_result&lt;- physical %&gt;% 
   filter(physical_3plus == &quot;yes&quot;) %&gt;% 
   summarise( yes_mean = mean(weight, na.rm = TRUE),
              yes_n = count(physical_3plus == &quot;yes&quot;),
              yes_sd = sd(weight, na.rm = TRUE),
              t_critical = qt(0.975, yes_n -1),
              se_yes = yes_sd / sqrt(yes_n),
              margin_of_error = t_critical * se_yes,
              yes_low_CI= yes_mean - margin_of_error,
              yes_high_CI= yes_mean + margin_of_error
              )

print(paste0(&quot;the confidence interval is &quot;,  as.numeric(yes_result[&#39;yes_low_CI&#39;]), &quot; - &quot;, as.numeric(yes_result[&#39;yes_high_CI&#39;]) ))</code></pre>
<pre><code>## [1] &quot;the confidence interval is 68.094807893518 - 68.8021328880692&quot;</code></pre>
<pre class="r"><code>#we can get a very similar result using the bootstrap approach for confidence intervals by infer package:

boot_dist1 &lt;- physical %&gt;% 
   filter(physical_3plus == &quot;yes&quot;) %&gt;% 

  specify(response = weight) %&gt;%
  # Generate bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  # Calculate mean of each bootstrap sample
  calculate(stat = &quot;mean&quot;)

boot_dist1</code></pre>
<pre><code>## Response: weight (numeric)
## # A tibble: 1,000 × 2
##    replicate  stat
##        &lt;int&gt; &lt;dbl&gt;
##  1         1  68.2
##  2         2  68.3
##  3         3  68.4
##  4         4  68.4
##  5         5  68.8
##  6         6  68.0
##  7         7  68.5
##  8         8  68.4
##  9         9  68.6
## 10        10  68.6
## # … with 990 more rows</code></pre>
<pre class="r"><code>percentile_ci1 &lt;- get_ci(boot_dist1, level = 0.95, type =&quot;percentile&quot;) 

#visualisation of the resulting bootstrap distribution and the CIs
  visualize(boot_dist1) +
  shade_ci(endpoints=percentile_ci1, fill=&quot;khaki&quot;) +
  geom_vline(xintercept = yes_result$yes_low_CI, colour =&quot;red&quot;) +
  geom_vline(xintercept = yes_result$yes_high_CI, colour = &quot;red&quot;) +
  NULL</code></pre>
<p><img src="/blogs/project5_files/figure-html/ci_using_formulas-1.png" width="672" /></p>
<pre class="r"><code>#physical_3plus == &quot;no&quot;
no_result &lt;-physical %&gt;% 
   filter(!is.na(physical_3plus)) %&gt;%
   filter(physical_3plus == &quot;no&quot;) %&gt;% 
   summarise( no_mean = mean(weight, na.rm = TRUE),
              no_n = count(physical_3plus == &quot;no&quot;),
              no_sd = sd(weight, na.rm = TRUE),
              t_critical = qt(0.975, no_n -1),
              se_no= no_sd / sqrt(no_n),
              margin_of_error = t_critical * se_no,
              no_low_CI= no_mean - margin_of_error,
              no_high_CI= no_mean + margin_of_error)

print(paste0(&quot;the confidence interval is &quot;,  as.numeric(no_result[&#39;no_low_CI&#39;]), &quot; - &quot;, as.numeric(no_result[&#39;no_high_CI&#39;]) ))</code></pre>
<pre><code>## [1] &quot;the confidence interval is 66.1286201312585 - 67.2191521213521&quot;</code></pre>
<pre class="r"><code>#we can also get a very similar result using the bootstrap approach for confidence intervals by infer package:

boot_dist2 &lt;- physical %&gt;% 
   filter(!is.na(physical_3plus)) %&gt;% 
   filter(physical_3plus == &quot;no&quot;) %&gt;% 
   specify(response = weight) %&gt;%
  # Generate bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  # Calculate mean of each bootstrap sample
  calculate(stat = &quot;mean&quot;)

percentile_ci &lt;- get_ci(boot_dist2, level = 0.95, type =&quot;percentile&quot;) 

#visualisation of the resulting bootstrap distribution and the CIs
  visualize(boot_dist2) +
  shade_ci(endpoints=percentile_ci, fill=&quot;khaki&quot;) +
  geom_vline(xintercept = no_result$no_low_CI, colour =&quot;red&quot;) +
  geom_vline(xintercept = no_result$no_high_CI, colour = &quot;red&quot;) +
  labs(title=&quot;Simulation-Based Bootsrap Distribution for No Answers&quot;) +
  NULL</code></pre>
<p><img src="/blogs/project5_files/figure-html/ci_using_formulas-2.png" width="672" /></p>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Null and alternative hypothesis:
H0 = there is no difference in the weight of those who exercise 3 times a week and more compared to those who do not.
H1 = there is a difference in the weight of those who exercise 3 times a week and more and those who do not.</p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = physical)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = 5.353, df = 7478.8, p-value = 8.908e-08
## alternative hypothesis: true difference in means between group yes and group no is not equal to 0
## 95 percent confidence interval:
##  1.124728 2.424441
## sample estimates:
## mean in group yes  mean in group no 
##          68.44847          66.67389</code></pre>
<p>Since the T value is 5 we can reject the NULL hypothesis, which means that we statistically sufficient evidence to say that there is a difference in the mean weight of those who work out more than 3 days a week and those who don’t.</p>
</div>
<div id="hypothesis-test-with-infer-package" class="section level2">
<h2>Hypothesis test with <code>infer</code> package</h2>
<pre class="r"><code>obs_diff &lt;- physical %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))

obs_diff</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: physical_3plus (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1  1.77</code></pre>
<p><strong>Simulating the test on the null distribution, which we will save as null.</strong></p>
<pre class="r"><code>  null_dist &lt;- physical %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/blogs/project5_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>The p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/project5_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## Warning: Please be cautious in reporting a p-value of 0. This result is an
## approximation based on the number of `reps` chosen in the `generate()` step. See
## `?get_p_value()` for more information.</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Since p value is very small, we can reject the null hypothesis that there is no difference in the weight of those who exercise 3 times a week and more compaed to those who do not.</p>
</div>
